Index:
  Background: Skip
Diagnostics:
  ClangTidy:
    FastCheckFilter: None
  UnusedIncludes: None
CompileFlags:
  Add: [ "-std=c++23", "-Wno-unknown-warning-option" ]
# Completion:
  # HeaderInsertion: Never
