Index:
  Background: Skip
Diagnostics:
  ClangTidy:
    FastCheckFilter: None
  UnusedIncludes: None
CompileFlags:
  Add:
    - -std=c++23
  Remove:
    - -fno-keep-inline-dllexport
    - -fmodules-ts
    - -fmodule-mapper=*
    - -fdeps-format=*
# Completion:
  # HeaderInsertion: Never
